import { create } from "zustand";
import { supabase } from "@/integrations/supabase/client";
import { USER_ID, DEFAULT_PROFILE } from "./constants";
import { mapWardrobeItem, mapProfile, mapOutfit, mapHistory } from "./mappers";
import type { WardrobeItem, UserProfile, Outfit, OutfitHistory } from "./types";
import { generateOutfits } from "./outfitGenerator";
import { generateAiOutfits } from "./generateAiOutfits";
import type { AiOutfitCandidate, AiSelectedOutfit } from "./aiOutfitSchema";

type ThemeMode = "light" | "dark";

type WardrobeItemUpdate = Pick<
  WardrobeItem,
  | "name"
  | "brand"
  | "category"
  | "subCategory"
  | "primaryColor"
  | "secondaryColor"
  | "colorFamily"
  | "pattern"
  | "styleTags"
  | "occasionTags"
  | "season"
>;

type State = {
  profile: UserProfile | null;
  items: WardrobeItem[];
  outfits: Outfit[];
  history: OutfitHistory[];
  loading: boolean;
  generating: boolean;
  generationNotice: string | null;
  theme: ThemeMode;
  loadAll: () => Promise<void>;
  saveProfile: (p: Partial<UserProfile>) => Promise<void>;
  addItem: (
    item: Omit<WardrobeItem, "id" | "userId" | "createdAt" | "timesWorn">,
    file?: File,
  ) => Promise<WardrobeItem>;
  updateItem: (id: string, item: WardrobeItemUpdate) => Promise<WardrobeItem>;
  deleteItem: (id: string) => Promise<void>;
  generate: () => Promise<void>;
  toggleSaved: (id: string) => Promise<void>;
  toggleFavorite: (id: string) => Promise<void>;
  markWorn: (outfitId: string, occasion?: string) => Promise<void>;
  setExplanation: (outfitId: string, text: string) => Promise<void>;
  renameOutfit: (outfitId: string, name: string) => Promise<void>;
  rateWear: (historyId: string, rating: number) => Promise<void>;
  deleteHistory: (historyId: string) => Promise<void>;
  toggleStored: (itemId: string) => Promise<void>;
  setTheme: (t: ThemeMode) => void;
  toggleTheme: () => void;
};

const initialTheme: ThemeMode =
  typeof window !== "undefined" && localStorage.getItem("closetiq-theme") === "dark"
    ? "dark"
    : typeof window !== "undefined" && localStorage.getItem("closetiq-theme") === "light"
      ? "light"
      : typeof window !== "undefined" &&
          window.matchMedia?.("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";

function applyTheme(t: ThemeMode) {
  if (typeof document === "undefined") return;
  document.documentElement.classList.toggle("dark", t === "dark");
  try {
    localStorage.setItem("closetiq-theme", t);
  } catch {}
}

function toAiCandidates(
  candidates: ReturnType<typeof generateOutfits>,
): AiOutfitCandidate[] {
  return candidates.map((candidate, index) => ({
    key: `candidate-${index + 1}`,
    topId: candidate.topId,
    bottomId: candidate.bottomId,
    shoesId: candidate.shoesId,
    jacketId: candidate.jacketId,
    localScore: candidate.score,
    occasionTags: candidate.occasionTags,
  }));
}

function localFallback(candidates: AiOutfitCandidate[]): AiSelectedOutfit[] {
  return candidates.slice(0, 24).map((candidate, index) => ({
    ...candidate,
    name: `Outfit ${index + 1}`,
    score: candidate.localScore,
    explanation: "Generated by ClosetIQ's deterministic compatibility engine.",
  }));
}

if (typeof document !== "undefined") {
  applyTheme(initialTheme);
}

export const useStore = create<State>((set, get) => ({
  profile: null,
  items: [],
  outfits: [],
  history: [],
  loading: false,
  generating: false,
  generationNotice: null,
  theme: initialTheme,

  setTheme: (t) => {
    applyTheme(t);
    set({ theme: t });
  },
  toggleTheme: () => {
    const next = get().theme === "dark" ? "light" : "dark";
    applyTheme(next);
    set({ theme: next });
  },

  loadAll: async () => {
    set({ loading: true });
    try {
      let { data: profileRow } = await supabase
        .from("user_profile")
        .select("*")
        .eq("id", USER_ID)
        .single();

      if (!profileRow) {
        const { data: created } = await supabase
          .from("user_profile")
          .insert({
            id: USER_ID,
            display_name: "User",
            skin_tone_hex: DEFAULT_PROFILE.skinToneHex,
            eye_color_hex: DEFAULT_PROFILE.eyeColorHex,
            hair_color_hex: DEFAULT_PROFILE.hairColorHex,
            skin_tone_type: DEFAULT_PROFILE.skinToneType,
            style_preferences: [],
          })
          .select()
          .single();
        profileRow = created;
      }

      const [itemsRes, outfitsRes, historyRes] = await Promise.all([
        supabase
          .from("wardrobe_items")
          .select("*")
          .eq("user_id", USER_ID)
          .order("created_at", { ascending: false })
          .limit(500),
        supabase
          .from("outfits")
          .select("*")
          .eq("user_id", USER_ID)
          .order("compatibility_score", { ascending: false })
          .limit(500),
        supabase
          .from("outfit_history")
          .select("*")
          .eq("user_id", USER_ID)
          .order("worn_date", { ascending: false })
          .limit(500),
      ]);

      set({
        profile: profileRow ? mapProfile(profileRow) : null,
        items: (itemsRes.data ?? []).map(mapWardrobeItem),
        outfits: (outfitsRes.data ?? []).map(mapOutfit),
        history: (historyRes.data ?? []).map(mapHistory),
        loading: false,
      });
    } catch (error) {
      console.error("Failed to load ClosetIQ data", error);
      set({ loading: false });
    }
  },

  saveProfile: async (p) => {
    const cur = get().profile;
    if (!cur) return;
    const next = { ...cur, ...p };
    const { error } = await supabase
      .from("user_profile")
      .update({
        display_name: next.displayName,
        skin_tone_hex: next.skinToneHex,
        eye_color_hex: next.eyeColorHex,
        hair_color_hex: next.hairColorHex,
        skin_tone_type: next.skinToneType,
        style_preferences: next.stylePreferences ?? [],
      })
      .eq("id", USER_ID);
    if (error) throw error;
    set({ profile: next });
  },

  addItem: async (item, file) => {
    const { data: doc, error } = await supabase
      .from("wardrobe_items")
      .insert({
        user_id: USER_ID,
        name: item.name,
        category: item.category,
        sub_category: item.subCategory ?? null,
        primary_color: item.primaryColor,
        secondary_color: item.secondaryColor ?? null,
        color_family: item.colorFamily,
        style_tags: item.styleTags ?? [],
        occasion_tags: item.occasionTags ?? [],
        pattern: item.pattern,
        season: item.season ?? [],
        brand: item.brand ?? null,
        times_worn: 0,
        is_stored: false,
      })
      .select()
      .single();

    if (error || !doc) throw error ?? new Error("Failed to create wardrobe item");
    let mapped = mapWardrobeItem(doc);

    if (file) {
      const { uploadWardrobeImage } = await import("./imageUpload");
      const url = await uploadWardrobeImage(file, mapped.id);
      const { data: updated, error: updateError } = await supabase
        .from("wardrobe_items")
        .update({ image_url: url })
        .eq("id", mapped.id)
        .select()
        .single();
      if (updateError) throw updateError;
      if (updated) mapped = mapWardrobeItem(updated);
    }

    set({ items: [mapped, ...get().items] });
    return mapped;
  },

  updateItem: async (id, item) => {
    const { data, error } = await supabase
      .from("wardrobe_items")
      .update({
        name: item.name.trim(),
        brand: item.brand?.trim() || null,
        category: item.category,
        sub_category: item.subCategory?.trim() || null,
        primary_color: item.primaryColor,
        secondary_color: item.secondaryColor || null,
        color_family: item.colorFamily,
        pattern: item.pattern,
        style_tags: item.styleTags,
        occasion_tags: item.occasionTags,
        season: item.season,
      })
      .eq("id", id)
      .eq("user_id", USER_ID)
      .select()
      .single();

    if (error || !data) throw error ?? new Error("Failed to update wardrobe item");
    const mapped = mapWardrobeItem(data);
    set({
      items: get().items.map((existing) => (existing.id === id ? mapped : existing)),
    });
    return mapped;
  },

  deleteItem: async (id) => {
    const { error } = await supabase
      .from("wardrobe_items")
      .delete()
      .eq("id", id)
      .eq("user_id", USER_ID);
    if (error) throw error;

    try {
      const { getWardrobeImagePath } = await import("./imageUpload");
      const path = await getWardrobeImagePath(id);
      await supabase.storage.from("wardrobe-images").remove([path]);
    } catch (storageError) {
      console.warn("Failed to remove wardrobe image", storageError);
    }

    set({
      items: get().items.filter((i) => i.id !== id),
      outfits: get().outfits.filter(
        (o) =>
          o.topId !== id &&
          o.bottomId !== id &&
          o.shoesId !== id &&
          o.jacketId !== id,
      ),
    });
  },

  generate: async () => {
    const { items, profile } = get();
    if (!profile) return;

    set({ generating: true, generationNotice: null });
    try {
      const activeItems = items.filter((item) => !item.isStored);
      const localCandidates = toAiCandidates(generateOutfits(activeItems, profile));
      if (localCandidates.length === 0) {
        set({
          generationNotice:
            "No valid outfit combinations were found. Add at least one top, bottom, and pair of shoes.",
        });
        return;
      }

      let selected: AiSelectedOutfit[];
      let notice: string;
      try {
        selected = await generateAiOutfits({
          items: activeItems,
          profile,
          candidates: localCandidates,
        });
        notice = `AI curated ${selected.length} outfits from ${localCandidates.length} valid combinations.`;
      } catch (error) {
        console.error("AI outfit curation failed; using local fallback", error);
        selected = localFallback(localCandidates);
        notice = `AI curation was unavailable, so ClosetIQ used local compatibility scoring. ${
          error instanceof Error ? error.message : ""
        }`.trim();
      }

      const { error: deleteError } = await supabase
        .from("outfits")
        .delete()
        .eq("user_id", USER_ID)
        .eq("is_saved", false);
      if (deleteError) throw deleteError;

      const { error: insertError } = await supabase.from("outfits").insert(
        selected.map((outfit) => ({
          user_id: USER_ID,
          top_id: outfit.topId,
          bottom_id: outfit.bottomId,
          shoes_id: outfit.shoesId,
          jacket_id: outfit.jacketId,
          compatibility_score: outfit.score,
          occasion_tags: outfit.occasionTags,
          name: outfit.name,
          ai_explanation: outfit.explanation,
          is_saved: false,
          is_favorite: false,
          worn_count: 0,
        })),
      );
      if (insertError) throw insertError;

      const { data, error: fetchError } = await supabase
        .from("outfits")
        .select("*")
        .eq("user_id", USER_ID)
        .order("compatibility_score", { ascending: false })
        .limit(500);
      if (fetchError) throw fetchError;

      set({
        outfits: (data ?? []).map(mapOutfit),
        generationNotice: notice,
      });
    } finally {
      set({ generating: false });
    }
  },

  toggleSaved: async (id) => {
    const outfit = get().outfits.find((candidate) => candidate.id === id);
    if (!outfit) return;
    const next = !outfit.isSaved;
    const { error } = await supabase.from("outfits").update({ is_saved: next }).eq("id", id);
    if (error) throw error;
    set({
      outfits: get().outfits.map((candidate) =>
        candidate.id === id ? { ...candidate, isSaved: next } : candidate,
      ),
    });
  },

  toggleFavorite: async (id) => {
    const outfit = get().outfits.find((candidate) => candidate.id === id);
    if (!outfit) return;
    const next = !outfit.isFavorite;
    const { error } = await supabase
      .from("outfits")
      .update({ is_favorite: next, is_saved: true })
      .eq("id", id);
    if (error) throw error;
    set({
      outfits: get().outfits.map((candidate) =>
        candidate.id === id
          ? { ...candidate, isFavorite: next, isSaved: true }
          : candidate,
      ),
    });
  },

  markWorn: async (outfitId, occasion) => {
    const today = new Date().toISOString().slice(0, 10);
    const outfit = get().outfits.find((candidate) => candidate.id === outfitId);
    if (!outfit) return;

    const { data: historyRow, error: historyError } = await supabase
      .from("outfit_history")
      .insert({
        user_id: USER_ID,
        outfit_id: outfitId,
        worn_date: today,
        occasion: occasion ?? null,
        notes: null,
      })
      .select()
      .single();
    if (historyError) throw historyError;

    const { error: outfitError } = await supabase
      .from("outfits")
      .update({ worn_count: outfit.wornCount + 1, is_saved: true })
      .eq("id", outfitId);
    if (outfitError) throw outfitError;

    const itemIds = [outfit.topId, outfit.bottomId, outfit.shoesId, outfit.jacketId].filter(
      Boolean,
    ) as string[];
    const updates = itemIds
      .map((id) => get().items.find((item) => item.id === id))
      .filter(Boolean) as WardrobeItem[];

    await Promise.all(
      updates.map((item) =>
        supabase
          .from("wardrobe_items")
          .update({
            times_worn: item.timesWorn + 1,
            last_worn: new Date().toISOString(),
          })
          .eq("id", item.id),
      ),
    );

    set({
      outfits: get().outfits.map((candidate) =>
        candidate.id === outfitId
          ? { ...candidate, wornCount: candidate.wornCount + 1, isSaved: true }
          : candidate,
      ),
      items: get().items.map((item) =>
        itemIds.includes(item.id)
          ? { ...item, timesWorn: item.timesWorn + 1, lastWorn: new Date().toISOString() }
          : item,
      ),
      history: historyRow ? [mapHistory(historyRow), ...get().history] : get().history,
    });
  },

  setExplanation: async (outfitId, text) => {
    const { error } = await supabase
      .from("outfits")
      .update({ ai_explanation: text })
      .eq("id", outfitId);
    if (error) throw error;
    set({
      outfits: get().outfits.map((outfit) =>
        outfit.id === outfitId ? { ...outfit, aiExplanation: text } : outfit,
      ),
    });
  },

  renameOutfit: async (outfitId, name) => {
    const { error } = await supabase.from("outfits").update({ name }).eq("id", outfitId);
    if (error) throw error;
    set({
      outfits: get().outfits.map((outfit) =>
        outfit.id === outfitId ? { ...outfit, name } : outfit,
      ),
    });
  },

  rateWear: async (historyId, rating) => {
    const { error } = await supabase
      .from("outfit_history")
      .update({ rating })
      .eq("id", historyId);
    if (error) throw error;
    set({
      history: get().history.map((entry) =>
        entry.id === historyId ? { ...entry, rating } : entry,
      ),
    });
  },

  deleteHistory: async (historyId) => {
    const { error } = await supabase.from("outfit_history").delete().eq("id", historyId);
    if (error) throw error;
    set({ history: get().history.filter((entry) => entry.id !== historyId) });
  },

  toggleStored: async (itemId) => {
    const item = get().items.find((candidate) => candidate.id === itemId);
    if (!item) return;
    const next = !item.isStored;
    const { error } = await supabase
      .from("wardrobe_items")
      .update({ is_stored: next })
      .eq("id", itemId)
      .eq("user_id", USER_ID);
    if (error) throw error;
    set({
      items: get().items.map((candidate) =>
        candidate.id === itemId ? { ...candidate, isStored: next } : candidate,
      ),
    });
  },
}));
