import assert from "node:assert/strict";
import test from "node:test";
import {
  normalizeAiOutfitSelection,
  type AiOutfitCandidate,
} from "../src/lib/aiOutfitSchema.ts";

const candidates: AiOutfitCandidate[] = [
  {
    key: "candidate-1",
    topId: "top-1",
    bottomId: "bottom-1",
    shoesId: "shoes-1",
    jacketId: null,
    localScore: 88,
    occasionTags: ["casual", "weekend"],
  },
  {
    key: "candidate-2",
    topId: "top-2",
    bottomId: "bottom-2",
    shoesId: "shoes-2",
    jacketId: "jacket-2",
    localScore: 91,
    occasionTags: ["smart-casual", "date-night"],
  },
];

test("keeps only candidates generated by the local rule engine", () => {
  const selected = normalizeAiOutfitSelection(
    {
      outfits: [
        {
          candidateKey: "candidate-1",
          name: "Weekend Navy",
          score: 94,
          occasionTags: ["casual"],
          explanation: "Balanced and easy to wear.",
        },
        {
          candidateKey: "invented-candidate",
          name: "Invented outfit",
          score: 100,
          occasionTags: ["office"],
          explanation: "This must be rejected.",
        },
      ],
    },
    candidates,
  );

  assert.equal(selected.length, 1);
  assert.equal(selected[0]?.key, "candidate-1");
  assert.equal(selected[0]?.topId, "top-1");
  assert.equal(selected[0]?.score, 90);
});

test("deduplicates selections and normalizes unsafe fields", () => {
  const selected = normalizeAiOutfitSelection(
    {
      outfits: [
        {
          candidateKey: "candidate-2",
          name: "<b>Date look</b>",
          score: 500,
          occasionTags: ["date-night", "office", "unknown"],
          explanation: "<script>Stylish</script>",
        },
        {
          candidateKey: "candidate-2",
          name: "Duplicate",
          score: 10,
        },
      ],
    },
    candidates,
  );

  assert.equal(selected.length, 1);
  assert.equal(selected[0]?.name.includes("<"), false);
  assert.equal(selected[0]?.explanation.includes(">"), false);
  assert.deepEqual(selected[0]?.occasionTags, ["date-night"]);
  assert.equal(selected[0]?.score, 94);
});
