/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as ClosetRouteImport } from './routes/closet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutfitsOutfitIdRouteImport } from './routes/outfits.$outfitId'
import { Route as ApiExplainRouteImport } from './routes/api.explain'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosetRoute = ClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsOutfitIdRoute = OutfitsOutfitIdRouteImport.update({
  id: '/$outfitId',
  path: '/$outfitId',
  getParentRoute: () => OutfitsRoute,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/gaps': typeof GapsRoute
  '/outfits': typeof OutfitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/api/explain': typeof ApiExplainRoute
  '/outfits/$outfitId': typeof OutfitsOutfitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/gaps': typeof GapsRoute
  '/outfits': typeof OutfitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/api/explain': typeof ApiExplainRoute
  '/outfits/$outfitId': typeof OutfitsOutfitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/gaps': typeof GapsRoute
  '/outfits': typeof OutfitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/api/explain': typeof ApiExplainRoute
  '/outfits/$outfitId': typeof OutfitsOutfitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/closet'
    | '/gaps'
    | '/outfits'
    | '/profile'
    | '/api/explain'
    | '/outfits/$outfitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/closet'
    | '/gaps'
    | '/outfits'
    | '/profile'
    | '/api/explain'
    | '/outfits/$outfitId'
  id:
    | '__root__'
    | '/'
    | '/closet'
    | '/gaps'
    | '/outfits'
    | '/profile'
    | '/api/explain'
    | '/outfits/$outfitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosetRoute: typeof ClosetRoute
  GapsRoute: typeof GapsRoute
  OutfitsRoute: typeof OutfitsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ApiExplainRoute: typeof ApiExplainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closet': {
      id: '/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof ClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits/$outfitId': {
      id: '/outfits/$outfitId'
      path: '/$outfitId'
      fullPath: '/outfits/$outfitId'
      preLoaderRoute: typeof OutfitsOutfitIdRouteImport
      parentRoute: typeof OutfitsRoute
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OutfitsRouteChildren {
  OutfitsOutfitIdRoute: typeof OutfitsOutfitIdRoute
}

const OutfitsRouteChildren: OutfitsRouteChildren = {
  OutfitsOutfitIdRoute: OutfitsOutfitIdRoute,
}

const OutfitsRouteWithChildren =
  OutfitsRoute._addFileChildren(OutfitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosetRoute: ClosetRoute,
  GapsRoute: GapsRoute,
  OutfitsRoute: OutfitsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ApiExplainRoute: ApiExplainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
